# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parsingPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(1550, 800)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 231, 91))
        self.label.setStyleSheet("font: 30pt \"DejaVu Sans\"; color:rgb(174,0,0)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(1240, 10, 231, 91))
        self.label_2.setStyleSheet("font: 30pt \"DejaVu Sans\"; color:rgb(174,0,0)")
        self.label_2.setObjectName("label_2")
        self.ph_display = QtWidgets.QPushButton(Dialog)
        self.ph_display.setGeometry(QtCore.QRect(550, 130, 201, 51))
        self.ph_display.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_display.setObjectName("ph_display")
        self.ph_difference = QtWidgets.QPushButton(Dialog)
        self.ph_difference.setGeometry(QtCore.QRect(770, 130, 201, 51))
        self.ph_difference.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_difference.setObjectName("ph_difference")
        self.tableAbs = QtWidgets.QTableWidget(Dialog)
        self.tableAbs.setGeometry(QtCore.QRect(0, 270, 651, 521))
        self.tableAbs.setStyleSheet("font: 8pt \"DejaVu Sans\";")
        self.tableAbs.setObjectName("tableAbs")
        self.tableAbs.setColumnCount(5)
        self.tableAbs.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAbs.setHorizontalHeaderItem(4, item)
        self.ph_errors = QtWidgets.QPushButton(Dialog)
        self.ph_errors.setGeometry(QtCore.QRect(990, 130, 201, 51))
        self.ph_errors.setStyleSheet("border-radius:20px;\n"
"font: 12pt \"DejaVu Sans\";color:rgb(255, 255, 255);\n"
"background-color:rgb(174,0,0);")
        self.ph_errors.setObjectName("ph_errors")
        self.cb_birim = QtWidgets.QComboBox(Dialog)
        self.cb_birim.setGeometry(QtCore.QRect(20, 140, 231, 27))
        self.cb_birim.setObjectName("cb_birim")
        self.cb_bolum = QtWidgets.QComboBox(Dialog)
        self.cb_bolum.setGeometry(QtCore.QRect(270, 140, 231, 27))
        self.cb_bolum.setObjectName("cb_bolum")
        self.tableStaff = QtWidgets.QTableWidget(Dialog)
        self.tableStaff.setGeometry(QtCore.QRect(660, 270, 881, 521))
        self.tableStaff.setStyleSheet("font: 8pt \"DejaVu Sans\";")
        self.tableStaff.setObjectName("tableStaff")
        self.tableStaff.setColumnCount(5)
        self.tableStaff.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStaff.setHorizontalHeaderItem(4, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Abs Api"))
        self.label_2.setText(_translate("Dialog", "Staff Api"))
        self.ph_display.setText(_translate("Dialog", "Display"))
        self.ph_difference.setText(_translate("Dialog", "Difference"))
        item = self.tableAbs.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Deparment"))
        item = self.tableAbs.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Title"))
        item = self.tableAbs.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableAbs.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Faculty"))
        item = self.tableAbs.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Image"))
        self.ph_errors.setText(_translate("Dialog", "Errors"))
        item = self.tableStaff.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Deparment"))
        item = self.tableStaff.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Title"))
        item = self.tableStaff.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Name"))
        item = self.tableStaff.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Email"))
        item = self.tableStaff.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Major Science"))
